version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: runnginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - reactdockercmps


  frontend:
    #build: ./frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: reactrun
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - reactdockercmps
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

networks:
  reactdockercmps:
    driver: bridge


